CREATE DATABASE CRUD_JAVA;

USE CRUD_JAVA;

CREATE TABLE TB_USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(45) NOT NULL,
    SENHA VARCHAR(45) NOT NULL
);

INSERT INTO TB_USUARIO(USUARIO, SENHA)
	VALUES('paulo', '123'),
    ('admin','admin');
